### ISSUE TITLE
disable dark mode + set status bar color transparent

### ISSUE THREAD

**Issue by its-me-debk007** [Jacinth-Mahanta/CalculatorApp#7]
The color palette is different, and action bar appears in night mode. I suggest to disable the night mode completely, since it's of no use.

Also, the status bar color is transparent/black in case of ios app.

<div align="center">
<img src="https://github.com/Jacinth-Mahanta/CalculatorApp/assets/81604986/daf56469-74f6-45bd-8a04-d57234140d02" width="200" height="400" />
</div>

**Comment by its-me-debk007** [comment]
I'm interested in this issue!

**Comment by Jacinth-Mahanta** [comment]
@its-me-debk007 The issue has been assigned to you.
